# Generated by Django 4.2.1 on 2023-05-14 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField()),
                ('passport_no', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Provider',
            fields=[
                ('pp_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('time', models.PositiveSmallIntegerField()),
                ('business', models.BooleanField()),
                ('eco_price', models.FloatField()),
                ('bus_price', models.FloatField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='shahair.airport')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='shahair.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('booking_class', models.CharField(choices=[('eco', 'Economy'), ('bus', 'Business')], max_length=3)),
                ('invoice_id', models.IntegerField(null=True)),
                ('payment_received', models.BooleanField(default=False)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shahair.flight')),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shahair.passenger')),
                ('payment_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shahair.payment_provider')),
            ],
        ),
    ]
