# Generated by Django 4.2.1 on 2023-05-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shahair', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
